service: olx-parser-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 60
  stage: dev
  region: us-east-1
  deploymentBucket: 
    name: ${sls:stage}-olx-parser-bucket-lambda
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - "ssm:Describe*"
            - "ssm:Get*"
            - "ssm:List*"
          Resource: '*'

functions:
  handleOlxAdvertisementsData:
    name: ${sls:stage}-handleOlxAdvertisementsData
    handler: handleOlxAdvertisementsData/index.handler
    environment: 
      ENV: ${sls:stage}
    events:
      - schedule:
          rate: rate(1 hour)
          enabled: true
